 nodeLinker: node-modules
enableGlobalCache: true

npmScopes:
  radix-ui:
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@radix-ui/react-dialog@*":
    dependencies:
      "@babel/runtime": "*"
  "@radix-ui/react-dropdown-menu@*":
    dependencies:
      "@babel/runtime": "*"
