services:
  - type: web
    name: equipment-manager
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        fromDatabase:
          name: equipment-db
          property: connectionString
      - key: VITE_DATABASE_URL
        fromDatabase:
          name: equipment-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REDIS_URL
        fromService:
          name: equipment-cache
          type: redis
          property: connectionString
      - key: VITE_STORAGE_URL
        value: https://emp-i6gc.onrender.com/api
      - key: VITE_NODE_ENV
        value: production

  - type: redis
    name: equipment-cache
    ipAllowList: []
    plan: starter

databases:
  - name: equipment-db
    databaseName: equipment
    user: equipment_admin
    plan: starter 