services:
  - type: web
    name: EMP
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        value: ${VITE_DATABASE_URL}
      - key: VITE_DATABASE_URL
        value: ${VITE_DATABASE_URL}
      - key: SESSION_SECRET
        generateValue: true
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: VITE_STORAGE_URL
        value: https://emp-i6gc.onrender.com/api
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_PUSHER_APP_KEY
        value: ${VITE_PUSHER_APP_KEY}
      - key: VITE_PUSHER_CLUSTER
        value: ${VITE_PUSHER_CLUSTER}
      - key: VITE_ADMIN_ID
        value: ${VITE_ADMIN_ID}
      - key: VITE_ADMIN_PASSWORD
        value: ${VITE_ADMIN_PASSWORD}
      - key: VITE_AGENT1_ID
        value: ${VITE_AGENT1_ID}
      - key: VITE_AGENT1_PASSWORD
        value: ${VITE_AGENT1_PASSWORD}

databases:
  - name: equipment-db
    databaseName: equipment_db
    user: equipment_db_user
    plan: starter
    region: singapore
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"