services:
  - type: web
    name: equipment-manager
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        value: ${VITE_DATABASE_URL}
      - key: VITE_DATABASE_URL
        value: ${VITE_DATABASE_URL}
      - key: SESSION_SECRET
        generateValue: true
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: VITE_STORAGE_URL
        value: https://emp-i6gc.onrender.com/api
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_PUSHER_APP_KEY
        sync: false
      - key: VITE_PUSHER_CLUSTER
        sync: false
      - key: VITE_ADMIN_ID
        sync: false
      - key: VITE_ADMIN_PASSWORD
        sync: false
      - key: VITE_AGENT1_ID
        sync: false
      - key: VITE_AGENT1_PASSWORD
        sync: false

  - type: redis
    name: equipment-cache
    ipAllowList: []
    plan: starter

databases:
  - name: equipment-db
    databaseName: equipment
    user: equipment_admin
    plan: starter
    region: singapore
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"

  - type: web
    name: pgadmin
    env: docker
    plan: starter
    disk:
      name: pgadmin
      mountPath: /var/lib/pgadmin
      sizeGB: 1
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        sync: false
      - key: PGADMIN_DEFAULT_PASSWORD
        sync: false
      - key: PGADMIN_LISTEN_PORT
        value: "80"
      - key: DATABASE_URL
        value: ${VITE_DATABASE_URL}

  - type: web
    name: pghero
    env: image
    image:
      url: docker.io/ankane/pghero:latest
    plan: starter
    envVars:
      - key: DATABASE_URL
        value: ${VITE_DATABASE_URL}
      - key: PGHERO_USERNAME
        sync: false
      - key: PGHERO_PASSWORD
        sync: false 