services:
  - type: web
    name: EMP
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        value: ${VITE_DATABASE_URL}
      - key: VITE_DATABASE_URL
        value: ${VITE_DATABASE_URL}
      - key: SESSION_SECRET
        generateValue: true
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: VITE_STORAGE_URL
        value: https://emp-i6gc.onrender.com/api
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_PUSHER_APP_KEY
        sync: false
      - key: VITE_PUSHER_CLUSTER
        sync: false
      - key: VITE_ADMIN_ID
        sync: false
      - key: VITE_ADMIN_PASSWORD
        sync: false
      - key: VITE_AGENT1_ID
        sync: false
      - key: VITE_AGENT1_PASSWORD
        sync: false

  - type: redis
    name: equipment-cache
    ipAllowList: []
    plan: starter

databases:
- name: equipment-db
  databaseName: equipment_db
  user: equipment_db_user
  plan: basic-256mb
  region: singapore
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
  diskSizeGB: 15
version: "1"

services:
- type: web
  name: pgAdmin-dpg-cujmioaj1k6c73cv6rhg-a
  runtime: docker
  repo: https://github.com/render-examples/pgadmin
  plan: starter
  envVars:
  - key: servers.json
    sync: false
  - key: pgpassfile
    sync: false
  - key: PORT
    sync: false
  - key: PGADMIN_SERVER_JSON_FILE
    sync: false
  - key: PGADMIN_LISTEN_PORT
    sync: false
  - key: PGADMIN_DEFAULT_PASSWORD
    sync: false
  - key: PGADMIN_DEFAULT_EMAIL
    sync: false
  - key: PGADMIN_DATABASE_USER
    sync: false
  - key: PGADMIN_DATABASE_NAME
    sync: false
  - key: PGADMIN_DATABASE_HOST
    sync: false
  - key: GUNICORN_THREADS
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
  disk:
    name: pgadmin
    mountPath: /var/lib/pgadmin
    sizeGB: 1
version: "1"

services:
- type: web
  name: PgHero-dpg-cujmioaj1k6c73cv6rhg-a
  runtime: image
  image:
    url: docker.io/ankane/pghero:latest
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    sync: false
  - key: PGHERO_PASSWORD
    sync: false
  - key: PGHERO_USERNAME
    sync: false
  - key: DATABASE_URL
    sync: false
  region: singapore
version: "1"