services:
  - type: web
    name: EMP
    runtime: node
    repo: https://github.com/Luciferhub44/EMP
    plan: starter
    buildCommand: |
      yarn install --frozen-lockfile --production=false
      yarn build
    startCommand: yarn preview
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: EMPDB
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_API_URL
        value: https://emp-m7tx.onrender.com
    healthCheckPath: /api/health
    healthCheckTimeout: 30
    autoDeploy: true
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /assets/*
        destination: /assets/$1
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: EMPDB
    databaseName: empdb_ihmy
    user: empdb_ihmy_user
    plan: basic-256mb
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"
    diskSizeGB: 15 
    