services:
  - type: web
    name: EMP
    runtime: node
    repo: https://github.com/Luciferhub44/EMP
    plan: starter
    env: node
    buildCommand: |
      yarn add -D vite typescript @vitejs/plugin-react-swc postcss autoprefixer @tailwindcss/postcss
      yarn install --frozen-lockfile
      yarn build
    startCommand: yarn start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: EMPDB
          property: connectionString
      - key: VITE_API_URL
        value: https://emp-fnly.onrender.com
      - key: NODE_ENV
        value: production
      - key: VITE_NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: EMPDB
    databaseName: empdb_ihmy
    user: empdb_ihmy_user
    plan: basic-256mb
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"
    diskSizeGB: 15 